name: ModelAPI
author: Ticxo
main: com.ticxo.modelapi.ModelAPI
version: 1.0
depend: [AdditionsAPI]
commands:
  disguise:
    usage: /<command> [modelId]
    description: Disguise as custom model
    permissions: modelapi.command.disguise
    permission-message: You not have have permission to use this command.
  undisguise:
    usage: /<command>
    description: Undisguise as custom model
    permissions: modelapi.command.undisguise
    permission-message: You not have have permission to use this command.
  state:
    usage: /<command> [add/remove] [state] <tick>
    description: Manipulate the state of the model
    permissions: modelapi.command.state
    permission-message: You not have have permission to use this command.